### ISSUE TITLE
无法发送Image消息

### ISSUE THREAD

**Issue by lincannm** [StageGuard/mirai-rhinojs-sdk#4]
```JavaScript
group.send(Image(null, null, path));
```
执行上面代码后，mirai console输出一个错误：
```
02:17:54 [ERROR] [MiraiAPIHTTP] java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessage(GroupImpl.kt:289)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$7.invokeSuspend(MessageRouteModule.kt:127)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$7.invoke(MessageRouteModule.kt)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:352)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)                         at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)                                                                               at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)                                                                                 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
不知道是谁的错，还是把issue发到这里吧

**Comment by StageGuard** [comment]
可以提供一下mirai-api-http版本吗

**Comment by lincannm** [comment]
> 可以提供一下mirai-api-http版本吗

1.7.2

**Comment by lincannm** [comment]
```JavaScript
//******订阅bot消息******
bot.subscribe({
    //群消息
    group: (group, sender, message) => {
            group.send(Image(null,null,"/root/source/1593095884281.png"));
    },
});
```
bot订阅消息部分是这么写的

**Comment by StageGuard** [comment]
已修复

**Comment by StageGuard** [comment]
另外`path`的是相对于`plugins/MiraiAPIHTTP/images/`的。

**Comment by lincannm** [comment]
谢谢
